# Generated by Django 5.1.3 on 2024-12-02 08:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=255, validators=[django.core.validators.EmailValidator(message='Enter a valid email address.')])),
                ('dob', models.DateField()),
            ],
        ),
    ]
